#!/bin/sh
# -------
# File:        aurex-pam-quota
# Description: Automagically sets user's quota on login
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------


test_mount_options(){
	# get the mount point
	MOUNT_POINT="$(df $1 |sed -e "s%^.* %%" |tail -1)"
	[ "$MOUNT_POINT" ] || return 1
	mount |grep "on $MOUNT_POINT " |grep -q "usrquota" || return 1
	return 0
}

test_quota(){
	quota --show-mntpoint --hide-device -u $QUOTA_USER |grep -q "^[[:blank:]]*$1" || return 1
	return 0
}

test_group(){
	for g in $QUOTA_GROUPS ; do
		if groups $QUOTA_USER |sed -e "s%^.*:% %;s%$% %" |grep -q " $g " ; then
			return 0
		fi
	done
	return 1
}


# main
# ----


[ -r /etc/aurex-pam-quota.conf ] || exit 0
. /etc/aurex-pam-quota.conf

# the file must provide blank delimited required lists for:
#QUOTA_GROUPS="ALUMNOS"

#QUOTA_FS="/datos"
#QUOTA_SL="60000MB"
#QUOTA_HL="75000MB"

QUOTA_USER="$PAM_USER"
if [ "$QUOTA_GROUPS" ] && [ "$QUOTA_USER" ] && test_group ; then
	for f in $QUOTA_FS ; do
		SL="${QUOTA_SL% *}"
		HL="${QUOTA_HL% *}"
		QUOTA_SL=${QUOTA_SL#* }
		QUOTA_HL=${QUOTA_HL#* }
		
		if [ "$SL" ] && [ "$HL" ] && test_mount_options "$f" && ! test_quota "$f" ; then
			# let's go to set quota
			quotatool -u $QUOTA_USER -b -q $SL -l $HL $f || true
		fi
	done
fi

exit 0

